---
title: "Cleaning & Exploratory Analysis of the Marijuana Prices Dataset"
author: "Alejandro Romero González"
affiliation: "Banco de México"
date: "21/02/2026"
---

```{r}
library(here)
library(dplyr)
library(janitor)
library(stringr)
library(ggplot2)
```

First, we load the raw dataset:
```{r}
RawData <- read.csv(here("Data", "Marijuana_Prices_in_Mexico_raw-3_utf8_bom.csv"))
```

The dataset contains the following structure:
```{r}
glimpse(RawData)
```

Second, we standarize variable names and build transaction fields:
```{r}
Data0 <- RawData |>
  clean_names() |>
  select(-response_id) |>
  mutate(
    quality = str_to_lower(str_trim(quality)),
    state = str_squish(state),
    municipality = str_squish(municipality),
    gender = str_squish(gender),
    education = str_squish(education),
    status = str_squish(status),
    relationship = str_squish(relationship),
    
    # unify amount/value across good vs bad columns
    quantity_g = coalesce(good_quantity, bad_quantity),
    value_mxn  = coalesce(good_value,  bad_value),
    price_mxn_g = value_mxn / quantity_g
  ) |>
  select(-good_quantity, -bad_quantity, -good_value, -bad_value)

Data0 <- Data0 %>%
  mutate(
    muni_code = str_extract(municipality, "\\d{5}$"),
    muni_name = str_trim(str_remove(municipality, "\\s*\\d{5}$"))
  )
```